Update tinyco-check-temp-idrac

diff --git a/nagscripts/tinyco-check-temp-idrac b/nagscripts/tinyco-check-temp-idrac
--- a/nagscripts/tinyco-check-temp-idrac
+++ b/nagscripts/tinyco-check-temp-idrac
@@ -6,10 +6,12 @@ PASSWORD="1pm1w00t!"
 #ip from args
 IDRAC=$1
 
-# heck inlet temperature
-echo "Checking inlet temperature on $IDRAC"
-TEMP=$(ipmitool -I lanplus -U $USERNAME -P $PASSWORD -L user -H $IDRAC sdr elist full | grep "Inlet Temp" | awk '{print $8}')
-if (( $(echo "$TEMP > 35" | bc -l) )); then
+# Check inlet temperature
+TEMP=$(ipmitool -I lanplus -U $USERNAME -P $PASSWORD -L user -H $IDRAC sdr elist full 2>&1)
+if [[ $TEMP == *"Error in open session response message : insufficient resources for session"* ]]; then
+    echo "Error: Insufficient resources for session on $IDRAC"
+    exit 3
+elif (( $(echo "$TEMP > 35" | bc -l) )); then
     echo "Critical temperature on $IDRAC"
     exit 2
 elif (( $(echo "$TEMP > 30" | bc -l) )); then
